# Generated by Django 2.1.7 on 2019-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='trivia_image',
            field=models.ImageField(default='pics/default.png', upload_to='pics'),
        ),
    ]
