# Generated by Django 2.1.7 on 2019-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0002_trivia_trivia_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.AlterField(
            model_name='trivia',
            name='trivia_text',
            field=models.TextField(max_length=200),
        ),
    ]
