# Generated by Django 2.1.7 on 2019-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0003_auto_20190326_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(default='static/whoisalive/images/background2.jpg', upload_to='pics'),
        ),
    ]
