# Generated by Django 2.1.7 on 2019-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0005_auto_20190329_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(default='pics/default.png', upload_to='pics'),
        ),
    ]
