# Generated by Django 2.1.7 on 2019-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0007_auto_20190330_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_desc',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_description',
            field=models.TextField(default='Description', max_length=500),
        ),
    ]
