# Generated by Django 2.1.7 on 2019-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0008_auto_20190330_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='trivia_image',
            field=models.ImageField(default='static/whoisalive/pics/default.png', upload_to='static/whoisalive/pics'),
        ),
    ]
