# Generated by Django 2.1.7 on 2019-03-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whoisalive', '0009_auto_20190330_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_text', models.TextField(max_length=200)),
                ('power_image', models.ImageField(default='static/whoisalive/pics/default.png', upload_to='static/whoisalive/pics')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoisalive.Hero', verbose_name='hero power')),
            ],
            options={
                'ordering': ('power_text',),
            },
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='hero',
        ),
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
